name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build required Xcode targets
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail

          DERIVED_DATA_PATH="${RUNNER_TEMP}/CovTraceDerivedData"

          xcodebuild clean build analyze \
            -project "CovTrace/CovTrace.xcodeproj" \
            -scheme "CovTrace Build All" \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty

          xcodebuild build analyze \
            -project "Example/Example.xcodeproj" \
            -scheme "Example" \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty
